# Defaults defines how the final config object is composed.  Order is important terravarmer will create infra in
# specified order specified in defaults object
defaults:
  # Shared Infrastructure
  - aws/shared/vpcs@shared.vpc.simple_vpc: simple_vpc
  - aws/shared/key_pairs@shared.key_pairs.hunter_labs_key: hunter_labs_key

  # Apps
  - aws/apps/sandbox@app.ec2.sandbox: sandbox


# Environment specific config lives here
environment:
  prod:
    aws_account: 222866594907
    region: "us-east-1"
    profile: "hunter_ops_prod"
    bucket: "hunter-ops-tfstate"


# Build section controls how the modules we defined are built
build:
  cloud_provider: "AWSProvider"  # Provider used to create all infra
  environment: "prod"            # Deployment environment must be one of dev|test|ppe|prod
  infra_shared: "create"         # Process shared infra, Must be one of create|destroy|pass
  infra_app: "create"            # Process application infra, must be one of create|destroy|pass
  terraform_mode: "apply"         # Must be one of plan|apply - Plan produces terraform plan only, apply will create or destroy infra
  debug: True                      # Set to True to enable verbose debugging
